# A removed configure input can leave both cache values and arbitrary headers.
set(fixture "${CMAKE_CURRENT_BINARY_DIR}/out/package-cache-fixture")
file(MAKE_DIRECTORY "${fixture}/source/modules")
file(WRITE "${fixture}/source/CMakeLists.txt" [=[
cmake_minimum_required(VERSION 4.4.3)
project(PackageCacheFixture LANGUAGES NONE)
list(PREPEND CMAKE_MODULE_PATH "${CMAKE_CURRENT_SOURCE_DIR}/modules")
find_package(PackageInputFixture QUIET)
add_custom_target(fixture-noop ALL COMMAND "${CMAKE_COMMAND}" -E true)
if(DEFINED PACKAGE_INPUT_MARKER)
  file(WRITE "${CMAKE_CURRENT_BINARY_DIR}/observed.txt" "${PACKAGE_INPUT_MARKER}")
else()
  file(WRITE "${CMAKE_CURRENT_BINARY_DIR}/observed.txt" "clean")
endif()
]=])
file(WRITE "${fixture}/source/modules/FindPackageInputFixture.cmake" [=[
set(PackageInputFixture_FOUND TRUE)
set(PACKAGE_INPUT_MARKER "untracked-input" CACHE STRING "Fixture contamination" FORCE)
file(WRITE "${CMAKE_CURRENT_BINARY_DIR}/obs-module.h" "/* leftover configure output */")
]=])
function(check_configure expected build_dir)
  execute_process(COMMAND "${CMAKE_COMMAND}" -S "${fixture}/source" -B "${build_dir}" ${ARGN}
    RESULT_VARIABLE result OUTPUT_QUIET ERROR_VARIABLE errors)
  if(NOT result EQUAL 0)
    message(FATAL_ERROR "Cache fixture configure failed: ${errors}")
  endif()
  file(READ "${build_dir}/observed.txt" actual)
  if(NOT actual STREQUAL expected)
    message(FATAL_ERROR "Cache fixture expected ${expected}, got ${actual}")
  endif()
endfunction()
check_configure("untracked-input" "${fixture}/build" --fresh)
file(REMOVE "${fixture}/source/modules/FindPackageInputFixture.cmake")
check_configure("untracked-input" "${fixture}/build")
check_configure("clean" "${fixture}/build" --fresh)
execute_process(COMMAND "${CMAKE_COMMAND}" --build "${fixture}/build" --config RelWithDebInfo --clean-first
  RESULT_VARIABLE result OUTPUT_QUIET ERROR_VARIABLE errors)
if(NOT result EQUAL 0)
  message(FATAL_ERROR "Cache fixture clean build failed: ${errors}")
endif()
if(NOT EXISTS "${fixture}/build/obs-module.h")
  message(FATAL_ERROR "Expected arbitrary header to survive --fresh and --clean-first")
endif()
string(RANDOM LENGTH 16 ALPHABET 0123456789abcdef suffix)
set(new_build "${fixture}/package-${suffix}/build")
check_configure("clean" "${new_build}")
if(EXISTS "${new_build}/obs-module.h")
  message(FATAL_ERROR "New package build tree contains a stale header")
endif()
message(STATUS "Package cache regression passed: cache persists without --fresh; arbitrary header survives --fresh/clean; new build tree contains neither")
