# A removed untracked configure input must not leave cache values in a package.
set(fixture "${CMAKE_CURRENT_BINARY_DIR}/out/package-cache-fixture")
file(MAKE_DIRECTORY "${fixture}/source/modules")
file(WRITE "${fixture}/source/CMakeLists.txt" [=[
cmake_minimum_required(VERSION 4.4.3)
project(PackageCacheFixture LANGUAGES NONE)
list(PREPEND CMAKE_MODULE_PATH "${CMAKE_CURRENT_SOURCE_DIR}/modules")
find_package(PackageInputFixture QUIET)
if(DEFINED PACKAGE_INPUT_MARKER)
  file(WRITE "${CMAKE_CURRENT_BINARY_DIR}/observed.txt" "${PACKAGE_INPUT_MARKER}")
else()
  file(WRITE "${CMAKE_CURRENT_BINARY_DIR}/observed.txt" "clean")
endif()
]=])
file(WRITE "${fixture}/source/modules/FindPackageInputFixture.cmake" [=[
set(PackageInputFixture_FOUND TRUE)
set(PACKAGE_INPUT_MARKER "untracked-input" CACHE STRING "Fixture contamination" FORCE)
]=])
function(check_configure expected)
  execute_process(COMMAND "${CMAKE_COMMAND}" -S "${fixture}/source" -B "${fixture}/build" ${ARGN}
    RESULT_VARIABLE result OUTPUT_QUIET ERROR_VARIABLE errors)
  if(NOT result EQUAL 0)
    message(FATAL_ERROR "Cache fixture configure failed: ${errors}")
  endif()
  file(READ "${fixture}/build/observed.txt" actual)
  if(NOT actual STREQUAL expected)
    message(FATAL_ERROR "Cache fixture expected ${expected}, got ${actual}")
  endif()
endfunction()
check_configure("untracked-input" --fresh)
file(REMOVE "${fixture}/source/modules/FindPackageInputFixture.cmake")
check_configure("untracked-input")
check_configure("clean" --fresh)
message(STATUS "Package cache regression passed: removed configure input persists without --fresh and is cleared with --fresh")
