# Offline regression for pinned extraction identity, prefix order and CMake cache reuse.
cmake_minimum_required(VERSION 3.25)
if(NOT DEPENDENCY_HELPER)
  set(DEPENDENCY_HELPER "${CMAKE_CURRENT_LIST_DIR}/../cmake/common/buildspec_common.cmake")
endif()
get_filename_component(DEPENDENCY_HELPER "${DEPENDENCY_HELPER}" ABSOLUTE)
# A no-language project exercises the real on-disk CMake cache without a compiler.
find_program(test_ninja NAMES ninja)
find_program(test_mingw_make NAMES mingw32-make)
if(test_ninja)
  set(generator_args -G Ninja "-DCMAKE_MAKE_PROGRAM=${test_ninja}")
elseif(WIN32 AND test_mingw_make)
  set(generator_args -G "MinGW Makefiles" "-DCMAKE_MAKE_PROGRAM=${test_mingw_make}")
elseif(WIN32)
  set(generator_args -G "Visual Studio 18 2026")
else()
  set(generator_args -G "Unix Makefiles")
endif()
string(RANDOM LENGTH 12 ALPHABET 0123456789abcdef test_id)
set(test_root "${CMAKE_CURRENT_LIST_DIR}/../out/dependency-prefix-${test_id}")
get_filename_component(test_root "${test_root}" ABSOLUTE)
set(deps "${test_root}/source/.deps")
set(version "2026-07-15")
set(prebuilt_prefix "${deps}/obs-deps-${version}-x64")
set(qt_prefix "${deps}/obs-deps-qt6-${version}-x64")
file(MAKE_DIRECTORY "${deps}")
# OBS 32.2.2 installs Development package configs directly into <prefix>/cmake.
foreach(package libobs obs-frontend-api)
  file(WRITE "${deps}/cmake/${package}Config.cmake" "set(${package}_origin pinned)\n")
endforeach()

function(make_package prefix kind package_version origin)
  file(WRITE "${prefix}/share/obs-deps/VERSION" "${package_version}\n")
  if(kind STREQUAL prebuilt)
    set(packages Probe)
  else()
    set(packages Qt6 Qt6Core)
  endif()
  foreach(package IN LISTS packages)
    file(WRITE "${prefix}/lib/cmake/${package}/${package}Config.cmake" "set(${package}_origin ${origin})\n")
  endforeach()
endfunction()

foreach(kind prebuilt qt6)
  make_package("${test_root}/seed/${kind}" "${kind}" "${version}" pinned)
  set(archive "${test_root}/upstream/${version}/${kind}-${version}.zip")
  file(MAKE_DIRECTORY "${test_root}/upstream/${version}")
  execute_process(COMMAND "${CMAKE_COMMAND}" -E tar cf "${archive}" --format=zip share lib
    WORKING_DIRECTORY "${test_root}/seed/${kind}" COMMAND_ERROR_IS_FATAL ANY)
  file(SHA256 "${archive}" ${kind}_hash)
  file(COPY "${archive}" DESTINATION "${deps}")
  # Reproduce a matching legacy checkout marker without trusted extraction identity.
  file(WRITE "${deps}/.dependency_${kind}_x64.sha256" "${${kind}_hash}")
endforeach()
file(WRITE "${test_root}/source/buildspec.json" "{\"dependencies\": {
  \"prebuilt\": {\"version\": \"${version}\", \"baseUrl\": \"file://${test_root}/upstream\", \"label\": \"Test prebuilt\", \"hashes\": {\"windows-x64\": \"${prebuilt_hash}\"}},
  \"qt6\": {\"version\": \"${version}\", \"baseUrl\": \"file://${test_root}/upstream\", \"label\": \"Test Qt\", \"hashes\": {\"windows-x64\": \"${qt6_hash}\"}}
}}")
set(project [=[
cmake_minimum_required(VERSION 3.25)
project(DependencySelection NONE)
include("@DEPENDENCY_HELPER@")
set(dependencies_dir "${CMAKE_CURRENT_SOURCE_DIR}/.deps")
set(dependencies_list prebuilt qt6)
set(arch x64)
set(platform windows-x64)
set(prebuilt_filename "prebuilt-VERSION.zip")
set(qt6_filename "qt6-VERSION.zip")
set(prebuilt_destination "obs-deps-VERSION-ARCH")
set(qt6_destination "obs-deps-qt6-VERSION-ARCH")
# Exercise the production dependency setup without compiling/downloading OBS.
function(_setup_obs_studio)
  list(GET CMAKE_PREFIX_PATH 0 first)
  list(GET CMAKE_PREFIX_PATH 1 second)
  if(NOT first STREQUAL "@prebuilt_prefix@" OR NOT second STREQUAL "@qt_prefix@")
    message(FATAL_ERROR "Pinned prefix order was not restored: ${CMAKE_PREFIX_PATH}")
  endif()
  find_package(Probe CONFIG REQUIRED)
  find_package(Qt6 CONFIG REQUIRED)
  find_package(Qt6Core CONFIG REQUIRED)
  find_package(libobs CONFIG REQUIRED)
  find_package(obs-frontend-api CONFIG REQUIRED)
  foreach(package Probe Qt6 Qt6Core libobs obs-frontend-api)
    if(NOT ${package}_origin STREQUAL pinned)
      message(FATAL_ERROR "External ${package} package selected: ${${package}_DIR}")
    endif()
  endforeach()
endfunction()
_check_dependencies()
]=])
string(CONFIGURE "${project}" project @ONLY)
file(WRITE "${test_root}/source/CMakeLists.txt" "${project}")

function(configure_case name prefixes external expected_error)
  execute_process(COMMAND "${CMAKE_COMMAND}" -S "${test_root}/source" -B "${test_root}/build" ${generator_args}
    "-DCMAKE_PREFIX_PATH=${prefixes}" "-DQt6_DIR=${external}/lib/cmake/Qt6"
    "-DQt6Core_DIR=${external}/lib/cmake/Qt6Core" "-Dlibobs_DIR=${external}/lib/cmake/libobs"
    "-Dobs-frontend-api_DIR=${external}/lib/cmake/obs-frontend-api"
    RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
  if(expected_error)
    if(result EQUAL 0 OR NOT "${output}${error}" MATCHES "${expected_error}")
      message(FATAL_ERROR "${name}: expected rejection (${expected_error}):\n${output}${error}")
    endif()
  elseif(NOT result EQUAL 0)
    message(FATAL_ERROR "${name}: configure failed:\n${output}${error}")
  endif()
  message(STATUS "PASS: ${name}")
endfunction()

# A newer, older, or same-version external tree, in either prefix order, cannot
# satisfy extraction reuse. Also poison package _DIR cache on every configure.
foreach(external_version 2026-08-01 2026-06-01 2026-07-15)
  set(external "${test_root}/external-${external_version}")
  make_package("${external}" prebuilt "${external_version}" external)
  make_package("${external}" qt6 "${external_version}" external)
  foreach(order external-first pinned-first)
    if(order STREQUAL external-first)
      set(prefixes "${external};${qt_prefix};${prebuilt_prefix}")
    else()
      set(prefixes "${prebuilt_prefix};${qt_prefix};${external}")
    endif()
    foreach(kind prebuilt qt6)
      if(kind STREQUAL prebuilt)
        set(prefix "${prebuilt_prefix}")
      else()
        set(prefix "${qt_prefix}")
      endif()
      make_package("${prefix}" "${kind}" "${version}" unverified)
      file(REMOVE "${prefix}/.obs-plugin-dependency.sha256")
      file(WRITE "${prefix}/unverified-sentinel" "must be removed by extraction")
    endforeach()
    configure_case("legacy marker / ${external_version} / ${order}" "${prefixes}" "${external}" "")
    foreach(prefix "${prebuilt_prefix}" "${qt_prefix}")
      if(EXISTS "${prefix}/unverified-sentinel")
        message(FATAL_ERROR "Unverified same-version prefix was reused: ${prefix}")
      endif()
      file(WRITE "${prefix}/reuse-sentinel" "must survive verified reuse")
    endforeach()
    configure_case("verified reuse / ${external_version} / ${order}" "${prefixes}" "${external}" "")
    foreach(prefix "${prebuilt_prefix}" "${qt_prefix}")
      if(NOT EXISTS "${prefix}/reuse-sentinel")
        message(FATAL_ERROR "Verified extraction was not reused: ${prefix}")
      endif()
    endforeach()
  endforeach()
  configure_case("verified reuse / ${external_version} / external-only" "${external}" "${external}" "")
endforeach()

# Missing/mismatched local identity or an invalid version/layout must re-extract.
foreach(kind prebuilt qt6)
  if(kind STREQUAL prebuilt)
    set(prefix "${prebuilt_prefix}")
  else()
    set(prefix "${qt_prefix}")
  endif()
  foreach(damage wrong-marker old-version new-version missing-version missing-package)
    if(damage STREQUAL missing-package AND kind STREQUAL prebuilt)
      continue()
    endif()
    file(WRITE "${prefix}/invalid-sentinel" "must be removed")
    if(damage STREQUAL wrong-marker)
      file(WRITE "${prefix}/.obs-plugin-dependency.sha256" "incorrect hash")
    elseif(damage STREQUAL old-version)
      file(WRITE "${prefix}/share/obs-deps/VERSION" "2026-06-01")
    elseif(damage STREQUAL new-version)
      file(WRITE "${prefix}/share/obs-deps/VERSION" "2026-08-01")
    elseif(damage STREQUAL missing-version)
      file(REMOVE "${prefix}/share/obs-deps/VERSION")
    else()
      file(REMOVE "${prefix}/lib/cmake/Qt6/Qt6Config.cmake")
    endif()
    configure_case("${kind} / ${damage}" "${prefixes}" "${external}" "")
    if(EXISTS "${prefix}/invalid-sentinel")
      message(FATAL_ERROR "Invalid extraction survived: ${kind} / ${damage}")
    endif()
  endforeach()
  # Removing the archive requires a fresh hash-checked download (local file URL).
  file(REMOVE "${deps}/${kind}-${version}.zip")
  configure_case("${kind} / missing archive" "${prefixes}" "${external}" "")
  file(WRITE "${deps}/${kind}-${version}.zip" "corrupt cache with valid extraction marker")
  configure_case("${kind} / corrupt archive during reuse" "${prefixes}" "${external}" "Dependency SHA256 mismatch")
  file(COPY_FILE "${test_root}/upstream/${version}/${kind}-${version}.zip" "${deps}/${kind}-${version}.zip")
endforeach()
message(STATUS "Dependency selection regressions passed (offline fixtures; no OBS/compiler required)")
