# Offline regression: only archive bytes, never extracted/build/install state,
# may cross from a developer dependency cache into an identified package.
cmake_minimum_required(VERSION 4.4.3)
if(NOT DEPENDENCY_HELPER_ROOT)
  set(DEPENDENCY_HELPER_ROOT "${CMAKE_CURRENT_LIST_DIR}/../cmake")
endif()
get_filename_component(DEPENDENCY_HELPER_ROOT "${DEPENDENCY_HELPER_ROOT}" ABSOLUTE)
string(RANDOM LENGTH 12 ALPHABET 0123456789abcdef test_id)
get_filename_component(test_root "${CMAKE_CURRENT_LIST_DIR}/../out/package-dependencies-${test_id}" ABSOLUTE)
set(source "${test_root}/source")
set(cache "${source}/.deps")
set(version "2026-07-15")
set(obs_version "32.2.2")
file(MAKE_DIRECTORY "${cache}" "${test_root}/upstream/${version}")
foreach(kind prebuilt qt6 obs-studio)
  if(kind STREQUAL prebuilt)
    set(filename "windows-deps-${version}-x64.zip")
    set(prefix "obs-deps-${version}-x64")
    set(payload "include/dependency.h")
  elseif(kind STREQUAL qt6)
    set(filename "windows-deps-qt6-${version}-x64.zip")
    set(prefix "obs-deps-qt6-${version}-x64")
    set(payload "lib/Qt6Core.lib")
  else()
    set(filename "${obs_version}.zip")
    set(prefix "obs-studio-${obs_version}")
    set(payload "src/input.c")
  endif()
  set(${kind}_prefix "${prefix}")
  set(${kind}_payload "${payload}")
  set(seed "${test_root}/seed/${kind}")
  if(kind STREQUAL obs-studio)
    file(WRITE "${seed}/${prefix}/${payload}" "archive-clean")
    set(entries "${prefix}")
    set(archive "${test_root}/upstream/${filename}")
  else()
    file(WRITE "${seed}/share/obs-deps/VERSION" "${version}\n")
    file(WRITE "${seed}/${payload}" "archive-clean")
    if(kind STREQUAL qt6)
      file(WRITE "${seed}/lib/cmake/Qt6/Qt6Config.cmake" "set(Qt6_FOUND TRUE)\n")
    endif()
    file(GLOB entries RELATIVE "${seed}" "${seed}/*")
    set(archive "${test_root}/upstream/${version}/${filename}")
  endif()
  execute_process(COMMAND "${CMAKE_COMMAND}" -E tar cf "${archive}" --format=zip ${entries}
    WORKING_DIRECTORY "${seed}" COMMAND_ERROR_IS_FATAL ANY)
  file(SHA256 "${archive}" ${kind}_hash)
  file(COPY "${archive}" DESTINATION "${cache}")
  set(${kind}_archive "${cache}/${filename}")
endforeach()
file(WRITE "${source}/buildspec.json" "{\"dependencies\": {
  \"prebuilt\": {\"version\": \"${version}\", \"baseUrl\": \"file://${test_root}/upstream\", \"label\": \"Test prebuilt\", \"hashes\": {\"windows-x64\": \"${prebuilt_hash}\"}},
  \"qt6\": {\"version\": \"${version}\", \"baseUrl\": \"file://${test_root}/upstream\", \"label\": \"Test Qt\", \"hashes\": {\"windows-x64\": \"${qt6_hash}\"}},
  \"obs-studio\": {\"version\": \"${obs_version}\", \"baseUrl\": \"file://${test_root}/upstream\", \"label\": \"Test OBS\", \"hashes\": {\"windows-x64\": \"${obs-studio_hash}\"}}
}}")
set(project [=[
cmake_minimum_required(VERSION 4.4.3)
project(PackageDependencyFixture NONE)
list(PREPEND CMAKE_MODULE_PATH "@DEPENDENCY_HELPER_ROOT@/common")
include(buildspec_common)
set(CMAKE_VS_PLATFORM_NAME x64)
# Keep real archive/extraction/root/package-cache code. Replace only the expensive
# OBS compile with assertions at its source/build/install boundary; real CI builds OBS.
function(_setup_obs_studio)
  if(OBS_PLUGIN_PACKAGE_BUILD)
    set(expected_root "${CMAKE_CURRENT_BINARY_DIR}/.deps")
    if(NOT dependencies_dir STREQUAL expected_root)
      message(FATAL_ERROR "Package reused developer dependency root")
    endif()
    foreach(stale "${dependencies_dir}/obs-studio-@obs_version@/build_x64/stale.obj" "${dependencies_dir}/lib/obs.lib")
      if(EXISTS "${stale}")
        message(FATAL_ERROR "Package reused OBS object or installed library")
      endif()
    endforeach()
  endif()
  if(EXPECT_TAINTED)
    set(expected "modified-after-extraction")
  else()
    set(expected "archive-clean")
  endif()
  foreach(payload "@prebuilt_prefix@/@prebuilt_payload@" "@qt6_prefix@/@qt6_payload@" "@obs-studio_prefix@/@obs-studio_payload@")
    file(READ "${dependencies_dir}/${payload}" actual)
    if(NOT actual STREQUAL expected)
      message(FATAL_ERROR "Dependency payload did not match expected boundary: ${payload}")
    endif()
  endforeach()
  if(EXPECT_TAINTED)
    foreach(payload "obs-studio-@obs_version@/build_x64/stale.obj" "lib/obs.lib")
      file(READ "${dependencies_dir}/${payload}" actual)
      if(NOT actual STREQUAL "modified-after-extraction")
        message(FATAL_ERROR "Developer reuse fixture did not preserve old OBS build/install")
      endif()
    endforeach()
  endif()
  if(NOT libobs_DIR STREQUAL "${dependencies_dir}/cmake" OR
      NOT obs-frontend-api_DIR STREQUAL "${dependencies_dir}/cmake" OR
      NOT Qt6_DIR STREQUAL "${dependencies_dir}/@qt6_prefix@/lib/cmake/Qt6")
    message(FATAL_ERROR "Package caches did not follow the selected dependency root")
  endif()
  file(WRITE "${dependencies_dir}/obs-studio-@obs_version@/build_x64/stale.obj" "${expected}")
  file(WRITE "${dependencies_dir}/lib/obs.lib" "${expected}")
endfunction()
include("@DEPENDENCY_HELPER_ROOT@/windows/buildspec.cmake")
]=])
string(CONFIGURE "${project}" project @ONLY)
file(WRITE "${source}/CMakeLists.txt" "${project}")
function(configure_case name build package_mode tainted expected_error)
  execute_process(COMMAND "${CMAKE_COMMAND}" -S "${source}" -B "${test_root}/${build}"
    "-DOBS_PLUGIN_PACKAGE_BUILD:BOOL=${package_mode}" "-DEXPECT_TAINTED:BOOL=${tainted}"
    "-DQt6_DIR=${cache}/${qt6_prefix}/lib/cmake/Qt6" "-Dlibobs_DIR=${cache}/cmake"
    "-Dobs-frontend-api_DIR=${cache}/cmake" "-DCMAKE_PREFIX_PATH=${cache}"
    RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
  if(expected_error)
    if(result EQUAL 0 OR NOT "${output}${error}" MATCHES "${expected_error}")
      message(FATAL_ERROR "${name}: expected rejection (${expected_error}): ${output}${error}")
    endif()
  elseif(NOT result EQUAL 0)
    message(FATAL_ERROR "${name}: ${output}${error}")
  endif()
  message(STATUS "PASS: ${name}")
endfunction()
configure_case("initial developer extraction" developer OFF OFF "")
foreach(payload "${prebuilt_prefix}/${prebuilt_payload}" "${qt6_prefix}/${qt6_payload}"
    "${obs-studio_prefix}/${obs-studio_payload}" "${obs-studio_prefix}/build_x64/stale.obj" "lib/obs.lib")
  file(WRITE "${cache}/${payload}" "modified-after-extraction")
endforeach()
# Valid VERSION/marker/archive hashes do not attest extracted/source/object/lib bytes.
configure_case("reproduce trusted developer reuse of modified payloads" developer OFF ON "")
configure_case("package ignores modified source/prebuilt/Qt/object/install" package-one ON OFF "")
# Poison a previous package too; another new package must still start from archives.
file(WRITE "${test_root}/package-one/.deps/${obs-studio_prefix}/${obs-studio_payload}" "modified-after-extraction")
configure_case("next package ignores previous package extraction" package-two ON OFF "")
foreach(kind prebuilt qt6 obs-studio)
  file(COPY_FILE "${${kind}_archive}" "${test_root}/archive-backup.zip")
  file(WRITE "${${kind}_archive}" "corrupt cached archive")
  configure_case("${kind} corrupt shared archive rejected" "corrupt-${kind}" ON OFF "Dependency SHA256 mismatch")
  file(COPY_FILE "${test_root}/archive-backup.zip" "${${kind}_archive}")
endforeach()
file(READ "${cache}/lib/obs.lib" original_library)
if(NOT original_library STREQUAL "modified-after-extraction")
  message(FATAL_ERROR "Package mutated the developer dependency installation")
endif()
message(STATUS "Package dependency isolation passed: 7 scenarios")
